name: Nix

on: push

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        env:
          NIX_VERSION: nix-2.4pre20210604_8e6ee1b
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run flake checks
        run: nix flake check -v --show-trace
